# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4330ac9f0eb5187276c33569e7472763245d04465e4dec2258e0e50408e20bcdcf5dc2241fa37fdff9ed985042f82f6ed9e7ddd4488bffcda76da587b59caff0

test:
  secret_key_base: 293149bd21738f4e8bd344e11758ccf4ed1f76d20ebc59d1422d3964d217ae482971bd459bff2c58c102657ae81db15c6cde86764bfc3a1953fa1b72941c4b40

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
